# Uncomment the next line to define a global platform for your project
 platform :ios, '12.2'

target 'Recipere' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'SSCalendarControl'

  # Pods for Recipere

  target 'RecipereTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecipereUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
